### ISSUE TITLE
Does the CLWB instruction guarantee the atomic flush of one cache line?

### ISSUE THREAD

**Issue by lizhenxin-github** [schencoding/lbtree#3]
Your paper has inspired me a lot, may I ask you one question.

You mentioned in the paper that the design of Entry Moving can flush Bitmap and KV in a cache line into PM directly using the CLWB instruction once. Does the CLWB instruction guarantee the atomic flush of the cache line? [Maybe not](https://stackoverflow.com/questions/65439089/is-clflush-or-clflushopt-atomic-when-system-crash). If the Bitmap has been flushed to PM but KV has not when the system crashes, is there a consistency problem?

**Comment by schencoding** [comment]
Suppose there are two writes A and B.  They go to the same cache line.   In a program, a thread performs write(A) then write(B) then  clwb/sfence.   There can be three possible cases after crash.  (1) old A , old B.  (2) new A, old B.  (3) new A, new B.  Please note that it is impossible to have old A and new B.  This is because the two writes to the same line are performed in the program order.  If B reaches the cache line in the CPU cache, A must have already been performed and have reached the CPU cache.

Now A is the KV and B is the bitmap.  All the three cases are good.  Case (1) and (2) are the old state.  The (old B) bitmap shows that the KV is still unused.  Case (3) is the new state.  Both the bitmap and the KV are up to date.

**Comment by lizhenxin-github** [comment]
Thank you for your answer.

**Comment by YalandHong** [comment]
Dear Dr. Chen,

I'm sorry but I'm still having doubts about this question.

I think you are missing the point. The author is talking about the persistent order, not the order of program store. That is, x86 store ordering (i.e. mfence) may not guarantee persistence ordering even within one line.

If the cache line is flushed from the left to the right, then Bitmap will be persisted before the corresponding KV.

The same question has also been proposed by #8. You need to provide some references about it.

Thanks!

**Comment by schencoding** [comment]
ADR guarantees that when a cache line reaches the memory controller, the entire cache line will be written to NVM whether or not there is a power failure.  Therefore, we do not need to worry about the locations of multiple writes in a cache line.
